export const reducerCases={
  SET_USER_INFO : "SET_USER_INFO",
  SET_NEW_USER : "SET_NEW_USER",
  SET_ALL_CONTACT_PAGE : "SET_ALL_CONTACT_PAGE",
  CHANGE_CURRENT_CHAT_USER : "CHANGE_CURRENT_CHAT_USER",
  SET_MESSAGES:"SET_MESSAGES",
  SET_SOCKET:"SET_SOCKET",
  ADD_MESSAGE:"ADD_MESSAGE",
  ONLINE_USERS:"ONLINE_USERS"
}